#!/usr/bin/env python3
"""Generate ready-to-paste theme code from a theme JSON's resolved tokens.

Examples:
  python3 export_theme.py catppuccin-mocha --target textual -o theme.py
  python3 export_theme.py catppuccin-mocha --target ink -o theme.mjs        # JS (valid in TS too)
  python3 export_theme.py catppuccin-mocha --target lipgloss -o theme.go    # package theme, lipgloss v2
  python3 export_theme.py catppuccin-mocha --target ratatui -o theme.rs
  python3 export_theme.py catppuccin-mocha --target gum > gum-theme.sh      # then: source gum-theme.sh
  python3 export_theme.py catppuccin-mocha --target css -o theme.css
  python3 export_theme.py catppuccin-mocha --target json -o theme.json

Targets: textual | ink | lipgloss | ratatui | gum | css | json (flat resolved theme:
id/name/appearance, terminal{background,foreground,cursor,selection_background,ansi[16]}, tokens{token:#hex}, ansi16{token:spec}). Values are truecolor hex from the resolved tokens
(references/themes/<id>.json); the frameworks downsample to 256/16 colors themselves.
Exit 0 = ok, 2 = theme not found / invalid / unknown target.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _theme import Theme, hex_to_rgb, load_theme, load_token_defs  # noqa: E402

GEN = "Generated by tui-design scripts/export_theme.py"


def header(th: Theme, prefix: str) -> list[str]:
    src = th.raw.get("sources", {})
    lines = [f"{GEN} - theme {th.id} ({th.name}, {th.appearance})"]
    lines += [f"source {k}: {v}" for k, v in src.items()]
    lines.append("tokens: themes/_tokens.json (resolved; tier-2 fallbacks applied)")
    return [prefix + l for l in lines]


def words(tok: str) -> list[str]:
    return [w for w in re.split(r"[.\-]", tok) if w]


def camel(tok: str) -> str:
    w = words(tok)
    return w[0] + "".join(x.title() for x in w[1:])


def pascal(tok: str) -> str:
    return "".join(x.title() for x in words(tok))


def snake(tok: str) -> str:
    return "_".join(words(tok))


# ------------------------------------------------------------------ textual

def export_textual(th: Theme) -> str:
    h = th.hex
    base = {
        "primary": "accent.primary", "secondary": "accent.secondary", "accent": "keyhint.key",
        "warning": "status.warning", "error": "status.error", "success": "status.success",
        "foreground": "fg.default", "background": "bg.base", "surface": "bg.surface", "panel": "bg.raised",
    }
    var = {
        "border": "border.focus", "border-blurred": "border.default",
        "block-cursor-foreground": "selection.fg", "block-cursor-background": "selection.bg",
        "block-cursor-blurred-foreground": "fg.default", "block-cursor-blurred-background": "selection.inactive.bg",
        "footer-foreground": "statusbar.fg", "footer-background": "statusbar.bg",
        "footer-key-foreground": "keyhint.key", "footer-description-foreground": "keyhint.desc",
        "input-cursor-background": "cursor.bg", "input-cursor-foreground": "cursor.fg",
        "input-selection-background": "text-selection.bg", "input-selection-foreground": "selection.fg",
        "scrollbar": "scrollbar.thumb", "scrollbar-background": "scrollbar.track",
        "link-color": "link", "text-muted": "fg.muted", "text-disabled": "fg.faint",
    }
    out = ['"""'] + header(th, "") + ['Textual >= 0.86: App.register_theme(THEME); App.theme = THEME.name', '"""',
                                    "", "from textual.theme import Theme", "", "THEME = Theme(", f'    name="{th.id}",']
    out += [f'    {k}="{h(t)}",' for k, t in base.items()]
    out += [f"    dark={th.appearance == 'dark'},", "    variables={"]
    out += [f'        "{k}": "{h(t)}",' for k, t in var.items()]
    out += ['        "block-cursor-text-style": "bold",', '        "link-style": "underline",', "    },", ")", ""]
    return "\n".join(out)


# ------------------------------------------------------------------ ink

def export_ink(th: Theme) -> str:
    defs = load_token_defs()
    pad = max(len(t) for t in defs) + 3
    out = header(th, "// ") + ["// Ink (hex colors work in <Text color> / <Box borderColor>); @inkjs/ui 2.0.0 theming per component.",
                               "// Run in a project with: npm i ink @inkjs/ui", "",
                               "import { defaultTheme, extendTheme } from '@inkjs/ui';", "",
                               "export const theme = {"]
    q = "'"
    out += [f"  {q + t + q + ':':<{pad}} {q}{th.hex(t)}{q}," for t in defs]
    out += ["};", "", "// Usage: <Text color={theme['status.error']} bold>failed</Text>",
            "//        <Box borderStyle=\"round\" borderColor={theme['border.focus']}>...</Box>", "",
            "// Object.fromEntries keeps the index signature, so byVariant[variant] also type-checks under strict TS.",
            "const byVariant = Object.fromEntries([",
            "  ['info', theme['status.info']], ['success', theme['status.success']],",
            "  ['warning', theme['status.warning']], ['error', theme['status.error']],", "]);", "",
            "export const inkTheme = extendTheme(defaultTheme, {",
            "  components: {",
            "    Spinner: { styles: { frame: () => ({ color: theme['accent.primary'] }) } },",
            "    ProgressBar: {",
            "      styles: {",
            "        completed: () => ({ color: theme['accent.primary'] }),",
            "        remaining: () => ({ color: theme['fg.faint'] }),",
            "      },",
            "    },",
            "    Badge: { styles: { label: () => ({ color: theme['fg.on-accent'] }) } },",
            "    Alert: {",
            "      styles: {",
            "        container: ({ variant }) => ({ borderColor: byVariant[variant] }),",
            "        icon: ({ variant }) => ({ color: byVariant[variant] }),",
            "      },",
            "    },",
            "    StatusMessage: { styles: { icon: ({ variant }) => ({ color: byVariant[variant] }) } },",
            "    Select: {",
            "      styles: {",
            "        focusIndicator: () => ({ color: theme['accent.primary'] }),",
            "        selectedIndicator: () => ({ color: theme['status.success'] }),",
            "        label: ({ isFocused, isSelected }) => ({",
            "          color: isFocused ? theme['accent.primary'] : isSelected ? theme['status.success'] : theme['fg.default'],",
            "        }),",
            "      },",
            "    },",
            "  },",
            "});",
            "// <ThemeProvider theme={inkTheme}>...</ThemeProvider>   (prop names per ink-ui source/theme.tsx; verify on upgrade)", ""]
    return "\n".join(out)


# ------------------------------------------------------------------ lipgloss (Go)

def _gofmt_block(rows: list[tuple[str, str]]) -> list[str]:
    w = max(len(n) for n, _ in rows)
    return [f"\t{n:<{w}} = {v}" for n, v in rows]


def export_lipgloss(th: Theme) -> str:
    defs = load_token_defs()
    c = {t: pascal(t) for t in defs}
    out = header(th, "// ") + [
        "// lipgloss v2 (charm.land/lipgloss/v2): colors are truecolor hex; downsampling to the terminal profile is automatic.",
        "// For a light+dark pair use lipgloss.LightDark(isDark)(light, dark) with two exports of this theme.", "",
        "package theme", "", 'import "charm.land/lipgloss/v2"', "", "// Colors: one variable per semantic token.", "var ("]
    out += _gofmt_block([(c[t], f'lipgloss.Color("{th.hex(t)}")') for t in defs])
    out += [")", ""]
    styles = [
        ("Base", f"lipgloss.NewStyle().Foreground({c['fg.default']}).Background({c['bg.base']})"),
        ("Title", f"lipgloss.NewStyle().Foreground({c['fg.title']}).Bold(true)"),
        ("Muted", f"lipgloss.NewStyle().Foreground({c['fg.muted']})"),
        ("Faint", f"lipgloss.NewStyle().Foreground({c['fg.faint']})"),
        ("Pane", f"lipgloss.NewStyle().Border(lipgloss.RoundedBorder()).BorderForeground({c['border.default']})"),
        ("PaneFocused", f"lipgloss.NewStyle().Border(lipgloss.RoundedBorder()).BorderForeground({c['border.focus']})"),
        ("Selected", f"lipgloss.NewStyle().Foreground({c['selection.fg']}).Background({c['selection.bg']}).Bold(true)"),
        ("StatusBar", f"lipgloss.NewStyle().Foreground({c['statusbar.fg']}).Background({c['statusbar.bg']}).Padding(0, 1)"),
        ("KeyHintKey", f"lipgloss.NewStyle().Foreground({c['keyhint.key']}).Bold(true)"),
        ("KeyHintDesc", f"lipgloss.NewStyle().Foreground({c['keyhint.desc']})"),
        ("LinkStyle", f"lipgloss.NewStyle().Foreground({c['link']}).Underline(true)"),  # color var is `Link`
    ]
    for s in ("success", "warning", "error", "info"):
        styles.append((s.title(), f"lipgloss.NewStyle().Foreground({c['status.' + s]})"))
    for s in ("success", "warning", "error", "info"):
        styles.append((f"Chip{s.title()}",
                       f"lipgloss.NewStyle().Foreground({c['fg.on-accent']}).Background({c['status.' + s]}).Bold(true).Padding(0, 1)"))
    out += ["// Styles: a few ready-made roles built from the colors above.", "var ("]
    out += _gofmt_block(styles)
    out += [")", ""]
    return "\n".join(out)


# ------------------------------------------------------------------ ratatui (Rust)

def rgb(th: Theme, tok: str) -> str:
    return "Color::Rgb({}, {}, {})".format(*hex_to_rgb(th.hex(tok)))


def export_ratatui(th: Theme) -> str:
    defs = load_token_defs()
    pal = [f"    pub const {snake(t).upper()}: Color = {rgb(th, t)};" for t in defs]
    C = lambda t: "palette::" + snake(t).upper()  # noqa: E731
    def st(fg=None, bg=None, mod=None, indent=4):
        parts = ["Style::new()"] + ([f".fg({C(fg)})"] if fg else []) + ([f".bg({C(bg)})"] if bg else []) \
            + ([f".add_modifier(Modifier::{mod})"] if mod else [])
        if len("".join(parts)) <= 60:           # rustfmt chain_width
            return "".join(parts)
        pad = "\n" + " " * (indent + 4)
        return parts[0] + pad + pad.join(parts[1:])
    fields = [
        ("root", st("fg.default", "bg.base")), ("content", st("fg.default", "bg.base")),
        ("title", st("fg.title", None, "BOLD")), ("muted", st("fg.muted")), ("faint", st("fg.faint")),
        ("borders", st("border.default")), ("borders_focused", st("border.focus")),
        ("selected", st("selection.fg", "selection.bg", "BOLD")), ("selected_inactive", st("fg.default", "selection.inactive.bg")),
        ("tabs", st("tab.inactive.fg", "statusbar.bg")), ("tabs_selected", st("tab.active.fg", "tab.active.bg", "BOLD")),
        ("statusbar", st("statusbar.fg", "statusbar.bg")), ("link", st("link", None, "UNDERLINED")),
        ("success", st("status.success")), ("warning", st("status.warning")), ("error", st("status.error")), ("info", st("status.info")),
        ("chip_success", st("fg.on-accent", "status.success", "BOLD")), ("chip_warning", st("fg.on-accent", "status.warning", "BOLD")),
        ("chip_error", st("fg.on-accent", "status.error", "BOLD")), ("chip_info", st("fg.on-accent", "status.info", "BOLD")),
    ]
    out = header(th, "// ") + [
        "// Pattern: ratatui examples/apps/demo2/src/theme.rs (a const Theme of Style fields per UI role).",
        "// Truecolor RGB; ratatui/the backend downsample on limited terminals.", "",
        "use ratatui::style::{Color, Modifier, Style};", "", "pub mod palette {", "    use super::Color;", ""] + pal + ["}", "",
        "pub struct KeyBinding {", "    pub key: Style,", "    pub description: Style,", "}", "", "pub struct Theme {"]
    out += [f"    pub {n}: Style," for n, _ in fields] + ["    pub key_binding: KeyBinding,", "}", "",
                                                         f"pub const THEME: Theme = Theme {{"]
    out += [f"    {n}: {v}," for n, v in fields]
    out += ["    key_binding: KeyBinding {", f"        key: {st('keyhint.key', None, 'BOLD', 8)},",
            f"        description: {st('keyhint.desc', None, None, 8)},", "    },", "};", ""]
    return "\n".join(out)


# ------------------------------------------------------------------ gum

def export_gum(th: Theme) -> str:
    h = th.hex
    spec = [
        ("CHOOSE", [("CURSOR", "accent.primary"), ("SELECTED", "status.success"), ("ITEM", "fg.default"), ("HEADER", "fg.title")]),
        ("FILTER", [("INDICATOR", "accent.primary"), ("MATCH", "search.match"), ("PROMPT", "accent.primary"),
                    ("PLACEHOLDER", "fg.faint"), ("TEXT", "fg.default"), ("HEADER", "fg.title")]),
        ("INPUT", [("PROMPT", "accent.primary"), ("PLACEHOLDER", "fg.faint"), ("CURSOR", "cursor.bg"), ("HEADER", "fg.title")]),
        ("CONFIRM", [("PROMPT", "fg.default")]),
        ("SPIN", [("SPINNER", "accent.primary"), ("TITLE", "fg.default")]),
        ("TABLE", [("HEADER", "table.header"), ("BORDER", "border.default")]),
        ("FILE", [("CURSOR", "accent.primary"), ("DIRECTORY", "accent.secondary"), ("FILE", "fg.default"), ("HEADER", "fg.title")]),
        ("WRITE", [("CURSOR", "cursor.bg"), ("LINE_NUMBER", "fg.faint"), ("PLACEHOLDER", "fg.faint"), ("PROMPT", "accent.primary")]),
    ]
    out = header(th, "# ") + ["# gum env vars: GUM_<CMD>_<PREFIX>_<ATTR> (charmbracelet/gum, style flags --<prefix>.foreground).",
                              "# Usage: source this file, then run gum. Names beyond the README examples: check `gum <cmd> --help`.", ""]
    for cmd, rows in spec:
        out += [f'export GUM_{cmd}_{p}_FOREGROUND="{h(t)}"' for p, t in rows]
        if cmd == "CONFIRM":
            out += [f'export GUM_CONFIRM_SELECTED_FOREGROUND="{h("fg.on-accent")}"',
                    f'export GUM_CONFIRM_SELECTED_BACKGROUND="{h("accent.primary")}"',
                    f'export GUM_CONFIRM_UNSELECTED_FOREGROUND="{h("fg.default")}"',
                    f'export GUM_CONFIRM_UNSELECTED_BACKGROUND="{h("bg.raised")}"']
        if cmd == "TABLE":
            out += [f'export GUM_TABLE_SELECTED_FOREGROUND="{h("selection.fg")}"',
                    f'export GUM_TABLE_SELECTED_BACKGROUND="{h("selection.bg")}"']
        out.append("")
    return "\n".join(out)


# ------------------------------------------------------------------ css

def export_css(th: Theme) -> str:
    defs = load_token_defs()
    out = header(th, "/* ")
    out = [l + " */" for l in out] + [":root {"]
    out += [f"  --{'-'.join(words(t))}: {th.hex(t)};" for t in defs]
    out += [f"  --ansi-{i}: {c};" for i, c in enumerate(th.ansi)]
    out += [f"  --terminal-bg: {th.background};", f"  --terminal-fg: {th.foreground};",
            f"  color-scheme: {th.appearance};", "}", ""]
    return "\n".join(out)


def export_json(th: Theme) -> str:
    """Flat resolved theme for non-Python consumers (proto-starters, shell, Go, Rust, Node)."""
    defs = load_token_defs()
    sel = th.selection_background
    data = {
        "id": th.id, "name": th.name, "appearance": th.appearance,
        "terminal": {"background": th.background, "foreground": th.foreground, "cursor": th.cursor,
                     "selection_background": sel, "ansi": list(th.ansi)},
        "tokens": {t: th.hex(t) for t in defs},
        "ansi16": {t: " ".join([str(th.ansi16[t][0]), *th.ansi16[t][1]]) for t in defs},
    }
    return json.dumps(data, indent=2) + "\n"


TARGETS = {"textual": export_textual, "ink": export_ink, "lipgloss": export_lipgloss,
           "ratatui": export_ratatui, "gum": export_gum, "css": export_css, "json": export_json}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Export a theme as framework code.", epilog=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("theme", help="theme id or path to theme .json")
    ap.add_argument("--target", required=True, choices=sorted(TARGETS))
    ap.add_argument("-o", "--out", help="write here instead of stdout")
    a = ap.parse_args(argv)
    try:
        th = load_theme(a.theme)
    except (FileNotFoundError, ValueError, KeyError, OSError) as e:
        print(f"export_theme: {e}", file=sys.stderr)
        return 2
    text = TARGETS[a.target](th)
    if a.out:
        Path(a.out).write_text(text, encoding="utf-8")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
